language: node_js

# use latest LTS Node.js release
node_js: lts/*

# run `npm ci` instead of `npm install`
install: npm ci

# run `build` script instead of `test`
script: npm run build

# keep the npm cache around to speed up installs
cache:
  directories: $HOME/.npm
